---
- hosts: os_init
  remote_user: root
  tasks:
    - include: sles11.yml
      when: ansible_distribution == "SLES" and ansible_distribution_major_version == "11"
    - include: sles12.yml
      when: ansible_distribution == "SLES" and ansible_distribution_major_version == "12"
    - include: rhel6.yml
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
    - include: rhel7.yml
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
