- name: export ITTE HUB http_proxy
  shell: export http_proxy=hubproxy.sh.cn.ao.ericsson.se
- name: eis_repo_url
  set_fact:
    eis_repo_url: "http://cnsheis0011.sh.cn.ao.ericsson.se/customrepo/eis"
- name: download the sles12 puppet rpm file
  get_url:
    url: "{{ eis_repo_url }}/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/{{ ansible_machine }}/eispuppet-3.7.3-1.sle12.x86_64.rpm"
    dest: /tmp/eispuppet-3.7.3-1.sle12.x86_64.rpm
- name: install the puppet rpm file
  yum:
    name: /tmp/eispuppet-3.7.3-1.sle12.x86_64.rpm
    state: present
- name: create link to puppet file
  file:
    src: /opt/puppet/bin/puppet
    dest: /usr/bin/puppet
- name: create facts.d directory 
  file:
    path: /etc/facter/facts.d/
    state: directory
- name: create ericsson.txt fact file
  file:
    path: /etc/facter/facts.d/ericsson.txt
    state: touch
- shell: echo 'site=cnsh' > /etc/facter/facts.d/ericsson.txt
